# permissions for end users to edit resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-editor-role
rules:
- apiGroups:
  - stack.octopipe.io
  resources:
  - resources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.octopipe.io
  resources:
  - resources/status
  verbs:
  - get
